spring.application.name=inventarios
# Conexión a mysql
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Configurar el patron del log (en lugar del archivo logback-spring.xml)
loggin.patttern.console=[%thread] %-5level: %logger - %msg%n
# Configurar el nivel de log (INFO)
loggin.level.root=INFO
# Opcional, configurar niveles por paquete
#loggin.level.gm.inventarios=DEBUG
#loggin.level.org.springframework=WARM
# Cambiar el puerto
#server.port=8081
spring.main.banner-mode=off

